Lesson 3: Application modes and pipeline deployment
red-p1xel/dv-campus-2021-magento pull request #4
Opened 2021-04-02 06:35 UTC by red-p1xel

2021-04-05 09:48 UTC, maksymz requested changes

2021-04-05 09:48 UTC, maksymz commented on .gitignore
> +!/var/db.sql.gz
@red-p1xel This rule does not make sense because another rule was added in the previous commit: "!/var/*.sql.gz". Though, this rule is more correct the the previous one, because database dump MUST be named `/var/db.sql.gz`

2021-04-05 09:48 UTC, maksymz commented on README.md
> +### Creating the database dump in `prod` environment
@red-p1xel Actually, this is a well-known general information that is not valuable for the project. Better not to add here the things like "How to connect to the MySQL server?" or "How to show all databases?" Every developer must know this or can find this in Google in seconds because this is a common knowledge. Otherwise we should add all MySQL and PHP documentation here.

2021-04-05 09:48 UTC, maksymz commented on app/etc/env.prod.php
> -    'MAGE_MODE' => 'developer',
@red-p1xel The file is incomplete and Magento can't be run. Please, compare this file with the file from the lesson #3 - https://github.com/maksymz/dv-campus-2020-2021-magento/blob/master/app/etc/env.prod.php

2021-04-05 09:48 UTC, maksymz commented on docker-compose-dev.yml
> +      - traefik.http.routers.vadymp-local-dev-http.rule=Host(`vadymp-dev.local`,`vadymp-keybay-dev.local`,`www.vadymp-keybay-dev.local`)
@red-p1xel Still missed `www` domain: `www.vadymp-dev.local` is not configured. The same for the production env.

2021-04-06 11:06 UTC, merged

2021-04-07 10:30 UTC, red-p1xel commented on docker-compose-dev.yml
> +      - traefik.http.routers.vadymp-local-dev-http.rule=Host(`vadymp-dev.local`,`vadymp-keybay-dev.local`,`www.vadymp-keybay-dev.local`)
@maksymz Thx for your code review. I fixed all this issues and pushed [commit](https://github.com/red-p1xel/dv-campus-2021-magento/commit/38935da0f81d1e1b791a4f5179831107d331c0ec) with changes to master-branch.